name = "mcp-server"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# ✅ ES Module formatını zorla
workers_dev = true

# Durable Objects tanımı
[[durable_objects.bindings]]
name = "MCP_OBJECT"
class_name = "MyMCP"

# ✅ Migrations (gerekirse)
[[migrations]]
tag = "v1"
new_classes = ["MyMCP"]